name: Blue Bullet

on:
  push:
      branches:
        - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    ## (2) 빌드 및 푸시 단계 (WAS 1)
    - name: Build JAR and Create/Push Docker Image (WAS1)
      run: ./gradlew clean bootJar dockerPush
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        IMAGE_TAG: "blue-bullet:was1"
    ## (3) 빌드 및 푸시 단계 (WAS 2)
    - name: Build JAR and Create/Push Docker Image (WAS2)
      run: ./gradlew clean bootJar dockerPush
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        IMAGE_TAG: "blue-bullet:was2"
    
    ## (4) 배포 단계
    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        
        # 원격 서버에서 실행할 스크립트
        script: |
          echo "Deployment started on remote server..."

          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          cd ${{ secrets.DEPLOY_PATH }} || exit 1 
          
          docker compose pull
          
          docker compose up -d --force-recreate
          
          echo "Deployment finished. Check service status with 'docker compose ps'"
